# Generated by Django 3.2.13 on 2022-07-09 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=19)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=19)),
                ('TypeOfEmergency', models.CharField(choices=[('Flood', 'Flood'), ('Medical Help', 'Medical Help'), ('Food and Shelter', 'Food and Shelter')], default='Flood', max_length=30)),
                ('RequestStatus', models.CharField(choices=[('HELP ALERT SEND TO AUTHORITIES', 'HELP ALERT SEND TO AUTHORITIES'), ('HELP TO YOUR LOCATION DEPLOYED', 'HELP TO YOUR LOCATION DEPLOYED'), ('OPERATION COMPLETED', 'OPERATION COMPLETED')], default='HELP ALERT SEND TO AUTHORITIES', max_length=30)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrowdSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=19)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=19)),
                ('category', models.CharField(choices=[('Roads', 'Roads'), ('Flood', 'Flood'), ('Landslide', 'Landslide'), ('Safehouse', 'Safehouse')], default='Flood', max_length=30)),
                ('image', models.ImageField(upload_to='crowdsourcing/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('HelpRequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api_floodmanagement.userhelprequest')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
