# Generated by Django 3.2.13 on 2022-07-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_floodmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForcastData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Site_Name', models.CharField(max_length=20)),
                ('River', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('District', models.CharField(max_length=20)),
                ('Day1', models.CharField(max_length=20)),
                ('Flood_Condition1', models.CharField(max_length=20)),
                ('Max_WL1', models.DecimalField(decimal_places=3, max_digits=5)),
                ('Day2', models.CharField(max_length=20)),
                ('Flood_Condition2', models.CharField(max_length=20)),
                ('Max_WL2', models.DecimalField(decimal_places=3, max_digits=5)),
                ('Day3', models.CharField(max_length=20)),
                ('Flood_Condition3', models.CharField(max_length=20)),
                ('Max_WL3', models.DecimalField(decimal_places=3, max_digits=5)),
                ('Day4', models.CharField(max_length=20)),
                ('Flood_Condition4', models.CharField(max_length=20)),
                ('Max_WL4', models.DecimalField(decimal_places=3, max_digits=5)),
                ('Day5', models.CharField(max_length=20)),
                ('Flood_Condition5', models.CharField(max_length=20)),
                ('Max_WL5', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
    ]
