# Generated by Django 3.2.13 on 2022-06-28 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_floodmanagement', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForcastDataDay1',
        ),
    ]
