# Generated by Django 3.2.13 on 2022-06-29 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_floodmanagement', '0002_delete_forcastdataday1'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=19)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=19)),
                ('TypeOfEmergency', models.CharField(choices=[('0', 'Flood'), ('1', 'Highway Safety'), ('2', 'Landslide'), ('3', 'Power Outage'), ('4', 'Medical Help'), ('5', 'Food')], default='0', max_length=30)),
                ('RequestStatus', models.CharField(choices=[('HELP ALERT SEND TO AUTHORITIES', 'HELP ALERT SEND TO AUTHORITIES'), ('HELP REQUEST RECIEVED ', 'HELP ALERT SEND TO AUTHORITIES'), ('HELP TO YOUR LOCATION DEPLOYED', 'HELP TO YOUR LOCATION DEPLOYED'), ('OPERATION COMPLETED', 'OPERATION COMPLETED')], default='HELP ALERT SEND TO AUTHORITIES', max_length=30)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('HelpRequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api_floodmanagement.userhelprequest')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
