# Generated by Django 3.2.13 on 2022-07-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_floodmanagement', '0002_forcastdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forcastdata',
            name='Max_WL1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='forcastdata',
            name='Max_WL2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='forcastdata',
            name='Max_WL3',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='forcastdata',
            name='Max_WL4',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='forcastdata',
            name='Max_WL5',
            field=models.CharField(max_length=20),
        ),
    ]
