# Generated by Django 3.2.13 on 2022-06-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_floodmanagement', '0003_comment_userhelprequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userhelprequest',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='userhelprequest',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='userhelprequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userhelprequest',
            name='TypeOfEmergency',
            field=models.CharField(choices=[('Flood', 'Flood'), ('Medical Help', 'Medical Help'), ('Food and Shelter', 'Food and Shelter')], default='Flood', max_length=30),
        ),
    ]
