# Generated by Django 3.2.13 on 2022-07-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_floodmanagement', '0003_auto_20220716_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdsource',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
