# Generated by Django 3.2.13 on 2022-08-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_floodmanagement', '0004_crowdsource_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloodForcastMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Site_Name', models.CharField(max_length=20)),
                ('River', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('District', models.CharField(max_length=20)),
                ('Day1', models.CharField(max_length=20)),
                ('Flood_Condition1', models.CharField(max_length=20)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=19)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=19)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
