# Generated by Django 3.2.13 on 2022-08-11 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_floodmanagement', '0006_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notification',
            new_name='notificationnn',
        ),
    ]
