# Generated by Django 3.2.13 on 2022-08-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_floodmanagement', '0007_rename_notification_notification_notificationnn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('Roads', 'Roads'), ('Flood', 'Flood'), ('Landslide', 'Landslide'), ('Safehouse', 'Safehouse')], default='Flood', max_length=30)),
                ('image', models.ImageField(upload_to='tips/')),
            ],
        ),
    ]
