# Generated by Django 3.2.13 on 2022-08-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_floodmanagement', '0008_tips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tips',
            name='category',
        ),
        migrations.AddField(
            model_name='tips',
            name='tips_category',
            field=models.CharField(choices=[('All', 'All'), ('Before Flood', 'Before FLood'), ('During Flood', 'During Flood'), ('After Flood', 'After Flood')], default='All', max_length=30),
        ),
    ]
