# Generated by Django 3.2.13 on 2022-08-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_floodmanagement', '0010_flooddataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flooddataset',
            name='water_level',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
