# Generated by Django 3.2.13 on 2022-08-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_floodmanagement', '0012_saftycheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inunation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('River', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=19)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=19)),
                ('water_level', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
    ]
