# Generated by Django 3.2.13 on 2022-09-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_floodmanagement', '0013_inunation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MsgBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('msg', models.TextField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='inunation',
            name='River',
        ),
        migrations.RemoveField(
            model_name='inunation',
            name='State',
        ),
    ]
